# Generated by Django 2.1.5 on 2020-05-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_title', models.CharField(max_length=10)),
                ('test_desc', models.TextField()),
            ],
        ),
    ]
