# Generated by Django 2.1.5 on 2020-06-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200601_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='raw_date_time',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
