# Generated by Django 2.1.5 on 2020-06-03 16:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_task_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 6, 3, 16, 23, 3, 338870, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
