# Generated by Django 2.1.5 on 2020-06-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_task_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='test_title',
            field=models.CharField(max_length=100),
        ),
    ]
